version: '3.3'
services:
  node:
    container_name: react-pdf-test
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development
    tty: true
